import { useMemo, useState } from 'react'
import { useAuth } from '../../context/AuthContext'

const filters = [['all', 'All'], ['signin', 'Seller Logins'], ['signup', 'Registrations'], ['product', 'Products'], ['payout', 'Payout Methods'], ['withdrawal', 'Withdrawals Requested'], ['balance', 'Balance Changes']]
const categoryFor = (log) => log.type?.includes('signin') ? 'signin' : log.type?.includes('signup') ? 'signup' : log.type?.includes('product') ? 'product' : log.type?.includes('withdrawal') || log.type?.includes('payout') ? 'withdrawal' : log.type?.includes('balance') || log.type?.includes('guarantee') ? 'balance' : log.icon === 'package' ? 'product' : 'other'
const iconFor = (log) => log.icon === 'signin' ? '↪' : log.icon === 'signup' ? '+' : log.icon === 'package' ? '◇' : log.icon === 'wallet' || log.icon === 'pay' ? '$' : log.icon === 'key' ? '⚿' : '~'

const AdminRecentActions = () => {
  const { adminLogs } = useAuth()
  const [filter, setFilter] = useState('all')
  const [query, setQuery] = useState('')
  const visible = useMemo(() => adminLogs.filter((log) => (filter === 'all' || categoryFor(log) === filter) && `${log.title} ${log.entity} ${log.type}`.toLowerCase().includes(query.toLowerCase())), [adminLogs, filter, query])
  const count = (category) => category === 'all' ? adminLogs.length : adminLogs.filter((log) => categoryFor(log) === category).length
  const groups = visible.reduce((result, log) => { const group = log.time === 'Just now' || /m ago|h ago/.test(log.time) ? 'Today' : /d ago/.test(log.time) ? 'Yesterday' : 'Older'; (result[group] ||= []).push(log); return result }, {})

  return <div className="mx-auto max-w-5xl space-y-5"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-indigo-600">Activity</p><h1 className="mt-1 text-3xl font-black text-gray-900">Recent Actions</h1><p className="mt-1 text-gray-500">Live timeline of your sellers' activity — logins, registrations, products, payouts, and balance changes.</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search seller, email, or action..." className="w-full rounded-2xl border-2 border-gray-100 bg-white px-5 py-4 text-lg shadow-sm focus:border-indigo-500 focus:outline-none" /><div className="flex gap-2 overflow-x-auto pb-1">{filters.map(([id, label]) => <button key={id} onClick={() => setFilter(id)} className={`whitespace-nowrap rounded-2xl px-4 py-3 font-bold ${filter === id ? 'bg-gray-900 text-white' : 'border border-gray-200 bg-white text-gray-600'}`}>{label} <span className="ml-1 opacity-70">{count(id)}</span></button>)}</div><div className="space-y-6">{Object.entries(groups).map(([group, logs]) => <section key={group}><h2 className="mb-3 px-2 text-sm font-black uppercase tracking-wider text-gray-500">{group}</h2><div className="relative space-y-3 rounded-3xl border border-gray-100 bg-white p-4 shadow-sm before:absolute before:bottom-8 before:left-10 before:top-8 before:w-px before:bg-indigo-100">{logs.map((log) => <article key={log.id} className="relative flex gap-4"><div className="z-10 flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-100 text-xl font-black text-indigo-700">{iconFor(log)}</div><div className="min-w-0 flex-1 border-b border-gray-100 pb-4 last:border-0"><div className="flex justify-between gap-3"><div><h3 className="font-black text-gray-900">{log.entity}</h3><p className="font-semibold text-gray-700">{log.title}</p><p className="mt-1 text-xs uppercase tracking-wider text-gray-400">{log.type || 'activity'}</p></div><time className="shrink-0 text-sm font-bold text-gray-400">{log.time}</time></div></div></article>)}</div></section>)}{!visible.length && <div className="rounded-3xl border-2 border-dashed border-gray-200 p-16 text-center font-bold text-gray-500">No actions match your filters.</div>}</div></div>
}
export default AdminRecentActions
